base_enterprise_context = (
    "Organization context and guidelines:\n\n"
    "This AI Agent Platform serves as a demonstration of enterprise-grade "
    "multi-agent AI systems. The platform is designed to work with "
    "international organizations and their employees who come from "
    "diverse countries and speak several languages. In 2024, this "
    "AI Agent Platform was developed to showcase comprehensive multi-agent "
    "capabilities for business solutions. The platform represents "
    "advanced AI integration using cutting-edge technologies. "
    "The platform includes various specialized agents such as "
    "General Agent, Finance Agent, HR Agent, and numerous others.\n\n"
    "When working with enterprise data, the system maintains "
    "professional standards and adapts to the organization's "
    "specific context and requirements. The agents are designed "
    "to handle diverse business scenarios and provide contextually "
    "appropriate responses based on organizational policies.\n\n"
    "The platform supports multiple business domains and can be "
    "customized for different industries and use cases. It "
    "demonstrates scalable architecture and modern AI capabilities "
    "for enterprise deployments."
)
